apiVersion: v1
kind: Service
metadata:
  name: feedback-frontend
  namespace: feedback
spec:
  type: LoadBalancer
  selector:
    app: feedback-frontend
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-frontend
  namespace: feedback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-frontend
  template:
    metadata:
      labels:
        app: feedback-frontend
    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKER_USERNAME/feedback-frontend:latest
          env:
            - name: VITE_API_BASE_URL
              value: http://feedback-backend.feedback.svc.cluster.local:8080/api
          ports:
            - containerPort: 80
